---
abstract: 'Template::Caribou wrapper for Dancer'
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  Dancer: '0'
  Dancer::Test: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Moose::Role: '0'
  Template::Caribou: v1.2.0
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer-Template-Caribou
provides:
  Dancer::Template::Caribou:
    file: lib/Dancer/Template/Caribou.pm
    version: v1.0.1
requires:
  Dancer::Config: '0'
  Dancer::Template::Abstract: '0'
  Module::Runtime: '0'
  Moo: '0'
  Moose::Util: '0'
  Template::Caribou: v1.2.0
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Dancer-Template-Caribou/issues
  homepage: https://github.com/yanick/Dancer-Template-Caribou
  repository: https://github.com/yanick/Dancer-Template-Caribou.git
version: 1.0.1
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributors:
  - 'Yanick Champoux <yanick@cpan.org>'
